spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: Rajesh@96
    url: jdbc:mysql://localhost:3306/organization_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: SVC-ORGANIZATION


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8085